function uniqueChance(){return Math.min(1,.15+(G.pity[G.currentDungeon]||0)*.08+stats().mf*.05)}
function bossLegend(){if(Math.random()<uniqueChance()){G.pity[G.currentDungeon]=0;let list=du().legs,un=list.filter(id=>!G.collection[id]),pool=un.length?un:list;return pool[Math.floor(Math.random()*pool.length)]}G.pity[G.currentDungeon]=(G.pity[G.currentDungeon]||0)+1;return null}
function gainXp(x){G.xp+=x;while(G.xp>=xpNeed()){G.xp-=xpNeed();G.lv++;G.hp=stats().hp;if(G.lv%5===0){G.traitPoints++;rollTraits()}log('⬆️ Lv.'+G.lv)}touch()}
function rollTraits(){let p=Object.keys(T).filter(id=>(G.traits[id]||0)<3);p.sort(()=>Math.random()-.5);G.traitChoices=p.slice(0,3)}
function milestoneCheck(){for(const m of [10,30,50,100]){let key=G.currentDungeon+'-'+m;if(G.best[G.currentDungeon]>m&&!G.milestones[key]){G.milestones[key]=true;G.mastery++;log('🏅 '+du().name+' '+m+'F初突破：Mastery +1')}}touch()}
function kill(){let e=G.enemy,s=stats(),gold=Math.floor((5+floor()*1.6)*e.goldM*s.gold);G.gold+=gold;G.totalKills++;if(e.boss)G.bossKills++;if(e.elite)G.eliteKills++;if(e.nem){G.nemesisKills++;G.nemesis=null}gainXp(Math.floor((7+floor()*1.15)*(e.boss?3:e.elite?1.8:1)));let leg=e.boss?bossLegend():null;if(leg)receive(makeItem(4,leg));else{let chance=Math.min(.93,.24+s.mf*.20+(e.elite?0.34:0)+(e.boss?0.28:0));if(Math.random()<chance)receive(makeItem(e.minRare));else log((e.boss?'👑 Boss撃破':'🦠 撃破')+' / +'+gold+'G')}if(G.mode==='normal'){G.runFloor[G.currentDungeon]++;G.best[G.currentDungeon]=Math.max(G.best[G.currentDungeon],G.runFloor[G.currentDungeon]);G.cycleBest[G.currentDungeon]=Math.max(G.cycleBest[G.currentDungeon]||1,G.runFloor[G.currentDungeon]);milestoneCheck()}G.enemy=null;spawn();touch()}
function heroHit(){if(!G.enemy)return;let s=stats(),d=s.atk;if(Math.random()<s.crit)d*=2.5;if(G.enemy.boss)d*=s.boss;if(G.enemy.elite)d*=s.elite;G.enemy.hp-=d;$('#hero').classList.add('hero-hit');$('#enemy-icon').classList.add('enemy-hit');setTimeout(()=>{$('#hero').classList.remove('hero-hit');$('#enemy-icon').classList.remove('enemy-hit')},130);if(G.enemy.hp<=0)kill()}
function enemyHit(){if(!G.enemy)return;let s=stats(),damage=Math.max(1,G.enemy.dmg*(1-s.dr));G.hp-=damage;if(G.hp<=0)die()}
function die(){let e=G.enemy;if(e&&(e.elite||e.nem)&&!e.boss){if(e.nem&&G.nemesis){G.nemesis.rank++;G.nemesis.homeFloor=Math.max(G.nemesis.homeFloor,floor());G.nemesis.readyAt=G.totalKills+8}else if(!G.nemesis)G.nemesis={name:'復讐の'+e.name.replace(/^復讐の/,''),icon:e.icon,rank:1,dungeon:G.currentDungeon,homeFloor:floor(),readyAt:G.totalKills+8}}if(G.mode==='normal')G.runFloor[G.currentDungeon]=cp();G.hp=stats().hp;G.enemy=null;G.deadUntil=Date.now()+3000;ht=0;et=0;log(G.mode==='boss'?'💀 Boss周回地点へ帰還。':'💀 '+G.runFloor[G.currentDungeon]+'Fチェックポイントへ帰還。');touch()}
function affText(x){let a=A[x?.id];if(!a)return'不明Affix';let tier=clamp(Math.floor(num(x.tier,1)),1,4),roman=['','I','II','III','IV'][tier],value=num(x.value,0);return a.n+' '+roman+' — '+a.desc+' +'+(value*100).toFixed(x.id==='regen'?2:1)+'%'}
