function uniqueChance(){return Math.min(1,.15+(G.pity[G.currentDungeon]||0)*.08+stats().mf*.05)}
function bossLegend(){if(Math.random()<uniqueChance()){G.pity[G.currentDungeon]=0;let list=du().legs,un=list.filter(id=>!G.collection[id]),pool=un.length?un:list;return pool[Math.floor(Math.random()*pool.length)]}G.pity[G.currentDungeon]=(G.pity[G.currentDungeon]||0)+1;return null}
function gainXp(x){G.xp+=x;while(G.xp>=xpNeed()){G.xp-=xpNeed();G.lv++;G.hp=stats().hp;if(G.lv%5===0){G.traitPoints++;rollTraits()}log('⬆️ Lv.'+G.lv)}touch()}
function rollTraits(){let p=Object.keys(T).filter(id=>(G.traits[id]||0)<3);p.sort(()=>Math.random()-.5);G.traitChoices=p.slice(0,3)}
function milestoneCheck(){for(const m of [10,30,50,100]){let key=G.currentDungeon+'-'+m;if(G.best[G.currentDungeon]>m&&!G.milestones[key]){G.milestones[key]=true;G.mastery++;log('🏅 '+du().name+' '+m+'F初突破：Mastery +1')}}touch()}
function flushGaugeFromEnemy(e){let mult=e.nem?1.5:e.boss?1.25:e.elite?1.1:1;if(G.mode==='boss')mult*=.6;return Math.max(0,(e.maxHp||0)/100*mult)}
function kill(){let e=G.enemy;if(!e)return;let s=stats(),gold=Math.floor((5+floor()*1.6)*e.goldM*s.gold);G.gold+=gold;G.totalKills++;G.flushGauge=(Number(G.flushGauge)||0)+flushGaugeFromEnemy(e);if(e.boss)G.bossKills++;if(e.elite)G.eliteKills++;if(e.nem){G.nemesisKills++;G.nemesis=null}gainXp(Math.floor((7+floor()*1.15)*(e.boss?3:e.elite?1.8:1)));let leg=e.boss?bossLegend():null;if(leg)receive(makeItem(4,leg));else{let type=e.boss?'boss':e.elite?'elite':'normal',chance=equipmentDropRate(type,s.mf);if(Math.random()<chance)receive(makeItem(e.minRare));else log((e.boss?'👑 Boss撃破':'🦠 撃破')+' / +'+gold+'G')}if(G.mode==='normal'){G.runFloor[G.currentDungeon]++;G.best[G.currentDungeon]=Math.max(G.best[G.currentDungeon],G.runFloor[G.currentDungeon]);G.cycleBest[G.currentDungeon]=Math.max(G.cycleBest[G.currentDungeon]||1,G.runFloor[G.currentDungeon]);milestoneCheck()}G.enemy=null;spawn();touch()}
function healHero(amount,proc=true){let s=stats(),before=G.hp;G.hp=Math.min(s.hp,G.hp+Math.max(0,amount));let healed=Math.max(0,G.hp-before);if(proc&&healed>0&&G.enemy&&s.healAtk>0){G.enemy.hp-=healed*s.healAtk;if(G.enemy.hp<=0)kill()}return healed}
function heroHit(){if(!G.enemy)return;let s=stats(),e=G.enemy,d=s.atk,hits=Math.min(10,e.hits||0);if(e.hp/e.maxHp>=.90)d*=1+s.first;if(hits>0)d*=1+s.combo*hits;let missing=clamp(1-G.hp/Math.max(1,s.hp),0,1);if(missing>0)d*=1+s.lastStand*missing;if(Math.random()<s.crit)d*=s.critMult;if(e.boss)d*=s.boss;if(e.elite)d*=s.elite;let before=e.hp;e.hp-=d;e.hits=(e.hits||0)+1;let dealt=Math.min(before,d);if(s.leech>0)healHero(dealt*s.leech,true);$('#hero').classList.add('hero-hit');$('#enemy-icon').classList.add('enemy-hit');setTimeout(()=>{$('#hero').classList.remove('hero-hit');$('#enemy-icon').classList.remove('enemy-hit')},130);if(G.enemy&&G.enemy.hp<=0)kill()}
function enemyHit(){if(!G.enemy)return;let s=stats(),damage=Math.max(1,G.enemy.dmg*(1-s.dr));G.hp-=damage;if(G.hp<=0){die();return}if(G.enemy&&s.counter>0){G.enemy.hp-=s.atk*s.counter;if(G.enemy.hp<=0)kill()}}
function die(){let e=G.enemy;if(e&&(e.elite||e.nem)&&!e.boss){if(e.nem&&G.nemesis){G.nemesis.rank++;G.nemesis.homeFloor=Math.max(G.nemesis.homeFloor,floor());G.nemesis.readyAt=G.totalKills+8}else if(!G.nemesis)G.nemesis={name:'復讐の'+e.name.replace(/^復讐の/,''),icon:e.icon,rank:1,dungeon:G.currentDungeon,homeFloor:floor(),readyAt:G.totalKills+8}}if(G.mode==='normal')G.runFloor[G.currentDungeon]=cp();G.hp=stats().hp;G.enemy=null;G.deadUntil=Date.now()+3000;ht=0;et=0;log(G.mode==='boss'?'💀 Boss周回地点へ帰還。':'💀 '+G.runFloor[G.currentDungeon]+'Fチェックポイントへ帰還。');touch()}
function affText(x){let a=A[x?.id];if(!a)return'不明Affix';let tier=clamp(Math.floor(num(x.tier,1)),1,4),roman=['','I','II','III','IV'][tier],v=num(x.value,0);if(x.id==='healstrike')return a.n+' '+roman+' — '+a.desc+' ×'+v.toFixed(2);if(x.id==='counter')return a.n+' '+roman+' — '+a.desc+' '+(v*100).toFixed(0)+'%';let digits=['regen','leech','combo'].includes(x.id)?2:1;return a.n+' '+roman+' — '+a.desc+' +'+(v*100).toFixed(digits)+'%'+(a.legacy?' (Legacy)':'')}
