function uniqueChance(id=G.currentDungeon){let f=D[id]?.clearFloor||30,mf=stats(G.gear,id,f).mf;return Math.min(1,.015+(G.pity[id]||0)*.0005+mf*.005)}
function bossLegend(){if(G.mode!=='boss')return null;if(Math.random()<uniqueChance()){G.pity[G.currentDungeon]=0;return du().legs[0]||null}G.pity[G.currentDungeon]=(G.pity[G.currentDungeon]||0)+1;return null}
function gainXp(x){G.xp+=x;while(G.xp>=xpNeed()){G.xp-=xpNeed();G.lv++;G.hp=stats().hp;if(G.lv%5===0){G.traitPoints++;rollTraits()}log('⬆️ Lv.'+G.lv)}touch()}
function rollTraits(){let p=Object.keys(T).filter(id=>(G.traits[id]||0)<3);p.sort(()=>Math.random()-.5);G.traitChoices=p.slice(0,3)}
function milestoneCheck(){for(const m of [10,20,30,50,100]){let key=G.currentDungeon+'-'+m;if(G.best[G.currentDungeon]>m&&!G.milestones[key]){G.milestones[key]=true;G.mastery++;log('🏅 '+du().name+' '+m+'F初到達：Mastery +1')}}touch()}
function flushGaugeFromEnemy(e){let mult=e.nem?1.5:e.boss?1.25:e.elite?1.1:1;if(G.mode==='boss')mult*=.6;return Math.max(0,(e.maxHp||0)/100*mult)}
function kill(){let e=G.enemy;if(!e)return;let s=stats(),lv=e.dungeonLv||dungeonLv(),gold=Math.floor((5+lv*1.6)*e.goldM*s.gold);G.gold+=gold;G.totalKills++;G.flushGauge=(Number(G.flushGauge)||0)+flushGaugeFromEnemy(e);if(e.boss)G.bossKills++;if(e.elite)G.eliteKills++;if(e.nem){G.nemesisKills++;G.nemesis=null}gainXp(Math.floor((7+lv*1.15)*(e.boss?3:e.elite?1.8:1)));let leg=e.bossDungeon?bossLegend():null;if(leg)receive(makeItem(4,leg,lv));else{let type=e.boss?'boss':e.elite?'elite':'normal',chance=equipmentDropRate(type,s.mf);if(Math.random()<chance)receive(makeItem(e.minRare,null,lv));else log((e.boss?'👑 Boss撃破':'🦠 撃破')+' / +'+gold+'G')}if(e.bossDungeon){G.bossCleared[G.currentDungeon]=true;G.enemy=null;G.hp=stats().hp;spawn();touch();return}if(G.mode==='normal'&&G.normalMode==='progress'){if(e.finalBoss&&!G.cleared[G.currentDungeon]){G.cleared[G.currentDungeon]=true;log('✅ '+du().name+' CLEAR！ Boss Dungeon「'+du().boss+'」解放。')}G.runFloor[G.currentDungeon]++;G.best[G.currentDungeon]=Math.max(G.best[G.currentDungeon],G.runFloor[G.currentDungeon]);G.cycleBest[G.currentDungeon]=Math.max(G.cycleBest[G.currentDungeon]||1,G.runFloor[G.currentDungeon]);milestoneCheck()}G.enemy=null;spawn();touch()}
function healHero(amount,proc=true,target=G.enemy){let s=stats(),before=G.hp;G.hp=Math.min(s.hp,G.hp+Math.max(0,amount));let healed=Math.max(0,G.hp-before);if(proc&&healed>0&&target&&G.enemy===target&&s.healAtk>0){target.hp-=healed*s.healAtk;if(target.hp<=0)kill()}return healed}
function heroStrike(mult=1,advanceCombo=true,label=''){if(!G.enemy)return null;let target=G.enemy,s=stats(),d=s.atk*mult,hits=Math.min(10,target.hits||0);if(target.hp/target.maxHp>=.90)d*=1+s.first;if(hits>0)d*=1+s.combo*hits;let missing=clamp(1-G.hp/Math.max(1,s.hp),0,1);if(missing>0)d*=1+s.lastStand*missing;let crit=Math.random()<s.crit,superCrit=false;if(crit){d*=s.critMult;let horizon=legendItem(G.gear,'horizon');if(horizon&&Math.random()<.10){let x=legendRollValue(horizon);d*=x;superCrit=true;log('💥 SUPER CRITICAL!! ×'+x.toFixed(1))}}if(target.boss)d*=s.boss;if(target.elite)d*=s.elite;let before=target.hp;target.hp-=d;if(advanceCombo)target.hits=(target.hits||0)+1;let dealt=Math.min(before,d);if(s.leech>0)healHero(dealt*s.leech,true,target);$('#hero').classList.add('hero-hit');$('#enemy-icon').classList.add('enemy-hit');setTimeout(()=>{$('#hero').classList.remove('hero-hit');$('#enemy-icon').classList.remove('enemy-hit')},130);if(label)log(label);return{target,dealt,crit,superCrit}}
function advanceLegendCounters(target){G.legendCounters=G.legendCounters||{reverse:0,rotcore:0};let reverse=legendItem(G.gear,'reverse'),rotcore=legendItem(G.gear,'rotcore');if(reverse)G.legendCounters.reverse=Math.min(5,(G.legendCounters.reverse||0)+1);else G.legendCounters.reverse=0;if(rotcore)G.legendCounters.rotcore=Math.min(4,(G.legendCounters.rotcore||0)+1);else G.legendCounters.rotcore=0;if(!target||G.enemy!==target||target.hp<=0)return;if(reverse&&G.legendCounters.reverse>=5){G.legendCounters.reverse=0;heroStrike(legendRollValue(reverse),false,'💥 逆流撃！');if(G.enemy!==target||target.hp<=0){if(G.enemy===target&&target.hp<=0)kill();return}}if(rotcore&&G.legendCounters.rotcore>=4&&G.enemy===target&&target.hp>0){G.legendCounters.rotcore=0;heroStrike(legendRollValue(rotcore),false,'☣️ 腐敗脈動！');healHero(stats().hp*.05,true,target);if(G.enemy===target&&target.hp<=0)kill()}}
function heroHit(){if(!G.enemy)return;let target=G.enemy,turbo=legendItem(G.gear,'turbobrush'),count=turbo?2:1,mult=turbo?legendRollValue(turbo):1;for(let i=0;i<count;i++){if(!G.enemy||G.enemy!==target||target.hp<=0)break;heroStrike(mult,true);if(G.enemy!==target)break;if(target.hp<=0)break}let targetAlive=G.enemy===target&&target.hp>0;advanceLegendCounters(targetAlive?target:null);if(G.enemy===target&&target.hp<=0)kill()}
function enemyHit(){if(!G.enemy)return;let s=stats(),damage=Math.max(1,G.enemy.dmg*(1-s.dr));G.hp-=damage;if(G.hp<=0){die();return}if(G.enemy&&s.counter>0){G.enemy.hp-=s.atk*s.counter;if(G.enemy.hp<=0)kill()}}
function die(){let e=G.enemy;if(e&&(e.elite||e.nem)&&!e.boss){if(e.nem&&G.nemesis){G.nemesis.rank++;G.nemesis.homeFloor=Math.max(G.nemesis.homeFloor,floor());G.nemesis.readyAt=G.totalKills+8}else if(!G.nemesis)G.nemesis={name:'復讐の'+e.name.replace(/^復讐の/,''),icon:e.icon,rank:1,dungeon:G.currentDungeon,homeFloor:floor(),readyAt:G.totalKills+8}}if(G.mode==='normal'&&G.normalMode==='progress')G.runFloor[G.currentDungeon]=e?.finalBoss?(du().clearFloor||30):cp();G.hp=stats().hp;G.enemy=null;G.deadUntil=Date.now()+3000;ht=0;et=0;if(G.mode==='boss')log('💀 Boss Dungeonで敗北。全回復して再挑戦。');else if(e?.finalBoss)log('💀 Final Bossで敗北。30Fから再挑戦。');else if(G.normalMode==='farm')log('💀 周回中に敗北。指定階層へ再出撃。');else log('💀 '+G.runFloor[G.currentDungeon]+'Fチェックポイントへ帰還。');touch()}
function affText(x){let a=A[x?.id];if(!a)return'不明Affix';let tier=clamp(Math.floor(num(x.tier,1)),1,4),roman=['','I','II','III','IV'][tier],v=num(x.value,0);if(x.id==='healstrike')return a.n+' '+roman+' — '+a.desc+' ×'+v.toFixed(2);if(x.id==='counter')return a.n+' '+roman+' — '+a.desc+' '+(v*100).toFixed(0)+'%';let digits=['regen','leech','combo'].includes(x.id)?2:1;return a.n+' '+roman+' — '+a.desc+' +'+(v*100).toFixed(digits)+'%'+(a.legacy?' (Legacy)':'')}
