const root=document.getElementById('poop212');if(!root)throw new Error('Missing #poop212 root');if(root.dataset.ready)throw new Error('Poop Dungeon already initialized');root.dataset.ready='1';const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
const R=[null,{n:'Common',m:1},{n:'Rare',m:1.45},{n:'Epic',m:2.08},{n:'Legendary',m:2.95},{n:'Mythic',m:4.2}],SLOTS={weapon:'⚔️ 武器',armor:'🛡️ 防具',charm:'💍 お守り'};
const D={sewer:{icon:'🚽',name:'地下便所跡',unlock:1,diff:1,hp:1,dmg:1,speed:1,gold:1,mf:0,elite:.08,bias:['fierce','vital'],desc:'標準。攻撃・生命系が出やすい。',loot:'攻撃 / HP',boss:'衛生主任',bossIcon:'🚽',legs:['reverse','seatplate']},rot:{icon:'☣️',name:'腐敗大聖堂',unlock:15,diff:1.35,hp:1.35,dmg:1.1,speed:1,gold:1.15,mf:.04,elite:.10,bias:['regen','vital','decay'],desc:'硬い敵が多い。再生・継戦向け。',loot:'再生 / HP / Elite',boss:'腐敗大司教',bossIcon:'🧟',legs:['rotcore','spore']},machine:{icon:'⚙️',name:'浄化機関区',unlock:30,diff:1.7,hp:1.15,dmg:1.25,speed:1.3,gold:1.2,mf:.06,elite:.12,bias:['quick','sharp','slayer'],desc:'敵が高速。速度・会心・Boss向け。',loot:'速度 / 会心 / Boss',boss:'浄化機関長',bossIcon:'🤖',legs:['turbobrush','shell']},gold:{icon:'👑',name:'黄金下水宮',unlock:50,diff:2.15,hp:1.35,dmg:1.35,speed:1.05,gold:1.75,mf:.12,elite:.14,bias:['greed','finder'],desc:'危険だが金と高レア掘りに特化。',loot:'Gold / Magic Find',boss:'黄金便器王',bossIcon:'👑',legs:['throne','midas']},cosmic:{icon:'🌌',name:'星間下水道',unlock:80,diff:3,hp:1.65,dmg:1.5,speed:1.25,gold:1.55,mf:.18,elite:.20,bias:['fierce','quick','sharp','finder'],desc:'最深部。Elite・Mythic・高Tier Affix。',loot:'Mythic / 高Tier Affix',boss:'事象排泄体',bossIcon:'🌀',legs:['cosmic','horizon']}};
const A={fierce:{n:'猛攻',stat:'atkPct',tiers:[[5,8],[9,13],[14,19],[20,27]],desc:'攻撃力'},quick:{n:'迅速',stat:'speedPct',tiers:[[4,7],[8,11],[12,16],[17,23]],desc:'攻撃速度'},sharp:{n:'会心',stat:'crit',tiers:[[2,3],[4,5],[6,8],[9,12]],desc:'会心率'},slayer:{n:'討伐',stat:'boss',tiers:[[6,10],[11,15],[16,22],[23,31]],desc:'Bossダメージ'},vital:{n:'生命',stat:'hpPct',tiers:[[6,10],[11,15],[16,22],[23,31]],desc:'最大HP'},regen:{n:'再生',stat:'regen',tiers:[[.25,.4],[.45,.7],[.75,1.05],[1.1,1.5]],desc:'秒間HP回復'},greed:{n:'黄金',stat:'gold',tiers:[[7,11],[12,18],[19,27],[28,40]],desc:'Gold獲得'},finder:{n:'探索',stat:'mf',tiers:[[2,3],[4,6],[7,9],[10,13]],desc:'Magic Find'},decay:{n:'腐食',stat:'elite',tiers:[[7,11],[12,18],[19,27],[28,38]],desc:'Eliteダメージ'}};
const L={reverse:{d:'sewer',slot:'weapon',n:'衛生主任の逆流槍',desc:'Bossダメージ +35%',mods:{boss:.35}},seatplate:{d:'sewer',slot:'armor',n:'便座鋼装甲',desc:'最大HP +30%',mods:{hpPct:.30}},rotcore:{d:'rot',slot:'charm',n:'腐敗心核',desc:'毎秒HP +2.0%',mods:{regen:.02}},spore:{d:'rot',slot:'armor',n:'胞子王外殻',desc:'Eliteダメージ +45%',mods:{elite:.45}},turbobrush:{d:'machine',slot:'weapon',n:'超蠕動ブラシ',desc:'攻撃速度 +28%',mods:{speedPct:.28}},shell:{d:'machine',slot:'armor',n:'浄化拒絶殻',desc:'被ダメージ -18%',mods:{dr:.18}},throne:{d:'gold',slot:'armor',n:'黄金便座鎧',desc:'Gold獲得 +55%',mods:{gold:.55}},midas:{d:'gold',slot:'charm',n:'ミダスの栓',desc:'Magic Find +15%',mods:{mf:.15}},cosmic:{d:'cosmic',slot:'weapon',n:'星間フラッシャー',desc:'攻撃 +32%、攻撃速度 +15%',mods:{atkPct:.32,speedPct:.15}},horizon:{d:'cosmic',slot:'charm',n:'事象の地平便座',desc:'会心 +12%、Bossダメージ +25%',mods:{crit:.12,boss:.25}}};
const T={rage:{i:'💪',n:'暴腸',d:'攻撃 +15%/Rank'},regen:{i:'❤️',n:'再生粘膜',d:'秒間HP回復 +0.6%/Rank'},greed:{i:'💰',n:'黄金便',d:'Gold +18%/Rank'},finder:{i:'🎁',n:'収集癖',d:'Magic Find +5%/Rank'},crit:{i:'🎯',n:'会心排泄',d:'会心率 +4%/Rank'},boss:{i:'👑',n:'便器殺し',d:'Bossダメージ +18%/Rank'}},SO={power:{i:'🔥',n:'魂圧',d:'全攻撃 +10%/Lv'},fortune:{i:'🎁',n:'深層運',d:'Magic Find +4%/Lv'},idle:{i:'🌙',n:'夢遊排泄',d:'放置報酬 +15%/Lv'},boss:{i:'👑',n:'王殺し',d:'Bossダメージ +12%/Lv'}},U={attack:{n:'⚔️ 腸圧',base:28},hp:{n:'❤️ 粘膜',base:32},speed:{n:'⚡ 蠕動',base:48},luck:{n:'🎁 幸運',base:60}},E=[['🦠','悪玉菌'],['🪱','配管ワーム'],['🐀','下水ネズミ'],['🤖','清掃ドローン'],['🧼','消毒ゴーレム'],['🟢','腐敗スライム']];
const maps=v=>Object.fromEntries(Object.keys(D).map(k=>[k,v]));
const safeNum=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,safeInt=(v,d=0,min=0,max=1e12)=>Math.max(min,Math.min(max,Math.floor(safeNum(v,d)))),safeStr=(v,d='',max=120)=>String(v??d).slice(0,max);
function cleanMap(src,def,min=0,max=1e9){let out=maps(def);for(const k of Object.keys(D))out[k]=safeInt(src?.[k],def,min,max);return out}
function cleanAff(x){if(!x||!A[x.id])return null;let tier=safeInt(x.tier,1,1,4),range=A[x.id].tiers[tier-1],value=safeNum(x.value,range[0]/100),lo=range[0]/100,hi=range[1]/100;return{id:x.id,tier,value:Math.max(lo,Math.min(hi,value))}}
function cleanItem(it){if(!it||!SLOTS[it.slot])return null;let legend=typeof it.legend==='string'&&L[it.legend]&&L[it.legend].slot===it.slot?it.legend:null,rar=safeInt(it.rar,legend?4:1,1,5);if(legend)rar=Math.max(4,rar);return{id:safeStr(it.id,Date.now().toString(36)+Math.random().toString(36).slice(2),80),slot:it.slot,rar,ilvl:safeInt(it.ilvl,1,1,100000),name:legend?L[legend].n:safeStr(it.name,'装備',80),atk:safeNum(it.atk,0),hp:safeNum(it.hp,0),speed:safeNum(it.speed,0),mf:safeNum(it.mf,0),aff:(Array.isArray(it.aff)?it.aff:[]).map(cleanAff).filter(Boolean).slice(0,4),legend,enh:safeInt(it.enh,0,0,999),invested:safeNum(it.invested,0),locked:!!it.locked}}
function cleanTraits(x){let out={};if(Array.isArray(x)){for(const id of x)if(T[id])out[id]=Math.min(3,(out[id]||0)+1)}else if(x&&typeof x==='object'){for(const id of Object.keys(T))out[id]=safeInt(x[id],0,0,3)}return out}
function fresh(k={}){return{v:213,lv:1,xp:0,gold:0,sludge:0,souls:k.souls||0,prestiges:k.prestiges||0,totalKills:k.totalKills||0,bossKills:k.bossKills||0,eliteKills:k.eliteKills||0,nemesisKills:k.nemesisKills||0,currentDungeon:'sewer',runFloor:maps(1),cycleBest:maps(1),best:k.best||maps(1),pity:k.pity||maps(0),milestones:k.milestones||{},mastery:k.mastery||0,collection:k.collection||{},soulTree:k.soulTree||{power:0,fortune:0,idle:0,boss:0},baseUp:{attack:0,hp:0,speed:0,luck:0},traits:{},traitPoints:0,traitChoices:[],gear:{weapon:null,armor:null,charm:null},inv:[],autoEquip:true,autoSalvage:1,equipFocus:'balanced',mode:'normal',farmFloor:10,nemesis:k.nemesis||null,enemy:null,hp:30,deadUntil:0,paused:false,simSpeed:1,recentDrops:[],offline:null,log:['💩が自律戦闘を開始した。']}}
function normalize(x){x=x&&typeof x==='object'?x:{};let f=fresh(),g=Object.assign(f,x);g.v=213;g.lv=safeInt(x.lv,1,1,100000);g.xp=Math.max(0,safeNum(x.xp,0));g.gold=Math.max(0,safeNum(x.gold,0));g.sludge=Math.max(0,safeNum(x.sludge,0));g.souls=safeInt(x.souls,0);g.prestiges=safeInt(x.prestiges,0);g.totalKills=safeInt(x.totalKills,0);g.bossKills=safeInt(x.bossKills,0);g.eliteKills=safeInt(x.eliteKills,0);g.nemesisKills=safeInt(x.nemesisKills,0);g.currentDungeon=D[x.currentDungeon]?x.currentDungeon:'sewer';g.runFloor=cleanMap(x.runFloor,1,1);g.best=cleanMap(x.best,1,1);g.cycleBest=cleanMap(x.cycleBest||x.runFloor,1,1);g.pity=cleanMap(x.pity,0,0,1000);g.milestones=x.milestones&&typeof x.milestones==='object'?x.milestones:{};g.mastery=safeInt(x.mastery,0,0,100000);g.collection=x.collection&&typeof x.collection==='object'?x.collection:{};g.soulTree={};for(const k of Object.keys(SO))g.soulTree[k]=safeInt(x.soulTree?.[k],0,0,10000);g.baseUp={};for(const k of Object.keys(U))g.baseUp[k]=safeInt(x.baseUp?.[k],0,0,10000);g.traits=cleanTraits(x.traits);g.traitPoints=safeInt(x.traitPoints,0,0,10000);g.traitChoices=(Array.isArray(x.traitChoices)?x.traitChoices:[]).filter(id=>T[id]&&(g.traits[id]||0)<3).slice(0,3);g.gear={weapon:null,armor:null,charm:null};for(const sl of Object.keys(SLOTS))g.gear[sl]=cleanItem(x.gear?.[sl]);g.inv=(Array.isArray(x.inv)?x.inv:[]).map(cleanItem).filter(Boolean).slice(0,200);g.autoEquip=x.autoEquip!==false;g.autoSalvage=safeInt(x.autoSalvage,1,0,2);g.equipFocus=['balanced','dps','boss','loot'].includes(x.equipFocus)?x.equipFocus:'balanced';g.mode=x.mode==='boss'?'boss':'normal';g.farmFloor=safeInt(x.farmFloor,10,1);let n=x.nemesis&&typeof x.nemesis==='object'?x.nemesis:null;g.nemesis=n&&D[n.dungeon]?{name:safeStr(n.name,'復讐者',80),icon:safeStr(n.icon,'☠️',8),rank:safeInt(n.rank,1,1,999),dungeon:n.dungeon,homeFloor:safeInt(n.homeFloor,1,1),readyAt:safeInt(n.readyAt,0)}:null;g.enemy=null;g.hp=Math.max(0,safeNum(x.hp,30));g.deadUntil=0;g.paused=!!x.paused;g.simSpeed=[1,2,4].includes(Number(x.simSpeed))?Number(x.simSpeed):1;g.recentDrops=(Array.isArray(x.recentDrops)?x.recentDrops:[]).map(r=>{let item=cleanItem(r?.item);return item?{item,action:safeStr(r.action,'',120),cmp:r.cmp&&typeof r.cmp==='object'?{dps:safeNum(r.cmp.dps,0),hp:safeNum(r.cmp.hp,0),boss:safeNum(r.cmp.boss,0),mf:safeNum(r.cmp.mf,0)}:null,time:safeNum(r.time,0)}:null}).filter(Boolean).slice(0,10);g.offline=x.offline&&typeof x.offline==='object'?{summary:safeStr(x.offline.summary,'',240),items:(Array.isArray(x.offline.items)?x.offline.items:[]).map(cleanItem).filter(Boolean).slice(0,12)}:null;g.log=(Array.isArray(x.log)?x.log:[]).map(v=>safeStr(v,'',180)).slice(0,8);if(!g.log.length)g.log=['💩が自律戦闘を開始した。'];return g}
let G=fresh(),last=performance.now(),ht=0,et=0,uiT=0,staticDirty=true;
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),fmt=v=>{v=num(v);return v<1e3?Math.floor(v).toLocaleString():v<1e6?(v/1e3).toFixed(1)+'K':v<1e9?(v/1e6).toFixed(1)+'M':(v/1e9).toFixed(1)+'B'},pct=v=>(v*100).toFixed(v<.1?1:0)+'%',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const gb=()=>Math.max(...Object.values(G.best)),runGb=()=>Math.max(...Object.values(G.cycleBest||maps(1))),floor=()=>G.mode==='boss'?G.farmFloor:G.runFloor[G.currentDungeon],du=()=>D[G.currentDungeon],cp=f=>Math.max(1,(f??floor())-(((f??floor())-1)%10)),xpNeed=()=>Math.floor(22*Math.pow(1.19,G.lv-1));
function deep(f=floor()){let hp=1,dmg=1,gold=1,mf=0,elite=0,label='通常領域';if(f>=31){hp*=1.22;dmg*=1.1;gold*=1.15;mf+=.02;label='深層 I'}if(f>=61){hp*=1.28;dmg*=1.15;gold*=1.2;mf+=.03;elite+=.04;label='深層 II'}if(f>=101){hp*=1.35;dmg*=1.2;gold*=1.25;mf+=.05;elite+=.07;label='深層 III'}return{hp,dmg,gold,mf,elite,label}}
function mods(gear=G.gear){let m={atk:0,hp:0,speed:0,mfFlat:0,atkPct:0,speedPct:0,crit:0,boss:0,elite:0,hpPct:0,regen:0,gold:0,dr:0,mf:0};for(const it of Object.values(gear)){if(!it)continue;let em=1+(it.enh||0)*.08;m.atk+=(it.atk||0)*em;m.hp+=(it.hp||0)*em;m.speed+=(it.speed||0)*em;m.mfFlat+=(it.mf||0)*em;for(const x of it.aff||[]){let a=A[x.id];if(a)m[a.stat]+=x.value}if(it.legend&&L[it.legend])for(const[k,v]of Object.entries(L[it.legend].mods))m[k]=(m[k]||0)+v}return m}
function stats(gear=G.gear,dun=G.currentDungeon,f=floor()){let m=mods(gear),dd=deep(f),tr=id=>G.traits[id]||0,ba=2+G.lv*.72+G.baseUp.attack*1.8,bh=30+G.lv*2+G.baseUp.hp*9,atk=(ba+m.atk)*(1+m.atkPct+tr('rage')*.15+G.soulTree.power*.1+G.mastery*.02),hp=(bh+m.hp)*(1+m.hpPct+G.mastery*.02),sp=Math.min(5,(.72+G.baseUp.speed*.055+m.speed*.012)*(1+m.speedPct)),crit=Math.min(.7,.05+m.crit+tr('crit')*.04),mf=Math.min(.85,G.baseUp.luck*.02+m.mfFlat*.01+m.mf+tr('finder')*.05+G.soulTree.fortune*.04+dd.mf+(D[dun]?.mf||0)),boss=1+m.boss+tr('boss')*.18+G.soulTree.boss*.12,elite=1+m.elite,regen=m.regen+tr('regen')*.006,gold=1+m.gold+tr('greed')*.18,dr=Math.min(.55,m.dr);return{ba,bh,atk,hp,sp,crit,mf,boss,elite,regen,gold,dr,dps:atk*sp*(1+crit*1.5),m}}
function survivability(s){return s.hp*(1+s.regen*25)/(1-s.dr)}
function setScore(gear,focus=G.equipFocus){let s=stats(gear),sur=survivability(s);if(focus==='dps')return s.dps;if(focus==='boss')return s.dps*s.boss;if(focus==='loot')return s.dps*.35+sur*.02+s.mf*900+s.gold*25;return s.dps*.68+sur*.055+s.mf*120+s.boss*8}
