function compareItem(it){let a=stats(),b=stats({...G.gear,[it.slot]:it}),delta=(x,y)=>x?((y/x)-1)*100:0;return{dps:delta(a.dps,b.dps),hp:delta(a.hp,b.hp),boss:delta(a.dps*a.boss,b.dps*b.boss),mf:(b.mf-a.mf)*100}}
function log(t){t=safeStr(t,'',180);G.log.unshift(t);G.log=G.log.slice(0,8);$('#notice').textContent=t}
function touch(){staticDirty=true}
function baseHp(f=floor()){return 12*Math.pow(1.112,f-1)*(1+f*.018)}
function canNemesis(){let x=G.nemesis,f=floor();return !!(x&&G.mode==='normal'&&x.dungeon===G.currentDungeon&&f>=Math.max(1,x.homeFloor-5)&&f<=x.homeFloor+8&&G.totalKills>=x.readyAt)}
function spawn(){if(G.deadUntil>Date.now())return;let f=floor(),d=du(),x=deep(f),boss=G.mode==='boss'||f%10===0,elite=false,nem=false,icon,name,hp=baseHp(f)*d.diff*d.hp*x.hp,dmg=Math.max(1,1.8*Math.pow(1.058,f-1)*d.diff*d.dmg*x.dmg),es=d.speed,gm=d.gold*x.gold,min=1,rank='NORMAL';if(boss){icon=d.bossIcon;name=d.boss;hp*=8.5;dmg*=2.2;gm*=5;min=2;rank='BOSS'}else if(canNemesis()&&Math.random()<.12){let n=G.nemesis;nem=true;elite=true;icon=n.icon;name=n.name;hp*=6.5*(1+n.rank*.38);dmg*=1.7*(1+n.rank*.14);gm*=7;min=3;rank='NEMESIS '+n.rank}else{let e=E[Math.floor(Math.random()*E.length)];icon=e[0];name=e[1];if(Math.random()<d.elite+x.elite){elite=true;let ts=[['巨大な',1.7,1,1],['黄金の',1.25,.9,2.5],['狂暴な',1.35,1.5,1.3],['変異した',1.45,1.1,1.5]],t=ts[Math.floor(Math.random()*ts.length)];name=t[0]+name;hp*=4*t[1];dmg*=1.4;es*=t[2];gm*=3.5*t[3];min=2;rank='ELITE'}}G.enemy={boss,elite,nem,icon,name,hp,maxHp:hp,dmg,enemySpeed:es,goldM:gm,minRare:min,rank};ht=0;et=0}
function tier(il,rar){let mx=1;if(il>=20||rar>=3)mx=2;if(il>=50||rar>=4)mx=3;if(il>=90||rar>=5)mx=4;let r=Math.random();return mx===4&&r>.74?4:mx>=3&&r>.58?3:mx>=2&&r>.40?2:1}
function aff(id,il,rar){let a=A[id],t=tier(il,rar),z=a.tiers[t-1],v=z[0]+Math.random()*(z[1]-z[0]);return{id,tier:t,value:v/100}}
function rarity(min=1){let s=stats(),r=Math.random()+s.mf*.22,v=r>.997?5:r>.955?4:r>.80?3:r>.48?2:1;return Math.max(min,v)}
function makeItem(min=1,leg=null,baseFloor=floor()){let slot=leg?L[leg].slot:Object.keys(SLOTS)[Math.floor(Math.random()*3)],rar=leg?4:rarity(min),il=Math.max(1,baseFloor+Math.floor(Math.random()*5)-2),mm=R[rar].m,pool=Object.keys(A);for(const b of du().bias)pool.push(b,b);let used=new Set(),aa=[];while(aa.length<Math.min(4,rar-1)){let id=pool[Math.floor(Math.random()*pool.length)];if(used.has(id))continue;used.add(id);aa.push(aff(id,il,rar))}let names={weapon:['配管剣','腸圧砲','浄化ブラシ'],armor:['粘膜鎧','下水外殻','配管装甲'],charm:['黄金栓','便座印章','腸内菌環']},it={id:Date.now().toString(36)+Math.random().toString(36).slice(2),slot,rar,ilvl:il,name:leg?L[leg].n:names[slot][Math.floor(Math.random()*names[slot].length)],atk:0,hp:0,speed:0,mf:0,aff:aa,legend:leg,enh:0,invested:0,locked:false};if(slot==='weapon'){it.atk=Math.floor((2+il*.72)*mm);it.speed=rar>=3?rar*1.15:0}if(slot==='armor'){it.hp=Math.floor((9+il*2.65)*mm);it.atk=rar>=3?Math.floor(il*.12*mm):0}if(slot==='charm'){it.mf=Math.floor((2+il*.16)*mm);it.atk=Math.floor(il*.17*mm);it.hp=Math.floor(il*.7*mm)}return it}
function salvageValue(it){return Math.max(1,Math.floor((R[it.rar]?.m||1)*(2+it.ilvl*.12)+(it.invested||0)*.70))}
function protectedItem(it){return !!(it&&(it.locked||it.legend||it.rar>=4))}
function itemValue(it){if(!it)return-1;return setScore({...G.gear,[it.slot]:it},'balanced')+(it.legend?500:0)+(it.rar>=4?700:0)+(it.rar>=5?300:0)}
function storeItem(it,{ignoreAuto=false,forceKeep=false}={}){if(!it)return'破棄';if(!ignoreAuto&&!protectedItem(it)&&it.rar<=G.autoSalvage){let v=salvageValue(it);G.sludge+=v;return'自動分解 → 🧪 +'+v}if(G.inv.length<36){G.inv.push(it);return'保管'}let evictable=G.inv.filter(x=>!protectedItem(x));if(protectedItem(it)||forceKeep){if(evictable.length){let worst=evictable.sort((a,b)=>itemValue(a)-itemValue(b))[0],i=G.inv.findIndex(x=>x.id===worst.id),v=salvageValue(worst);G.inv.splice(i,1);G.sludge+=v;G.inv.push(it);return(forceKeep?'旧装備保護':'保護品')+'のため低価値装備を分解 → 🧪 +'+v}G.inv.push(it);return(forceKeep?'旧装備保護':'保護品')+'のため上限超過で保管'}if(!evictable.length){let v=salvageValue(it);G.sludge+=v;return'保管枠が保護品のみ → 自動分解 🧪 +'+v}let worst=evictable.sort((a,b)=>itemValue(a)-itemValue(b))[0];if(itemValue(it)>itemValue(worst)){let i=G.inv.findIndex(x=>x.id===worst.id),v=salvageValue(worst);G.inv.splice(i,1);G.sludge+=v;G.inv.push(it);return'低価値装備を入替分解 → 🧪 +'+v}let v=salvageValue(it);G.sludge+=v;return'満杯のため自動分解 → 🧪 +'+v}
function recordDrop(it,action,cmp){G.recentDrops.unshift({item:JSON.parse(JSON.stringify(it)),action,cmp,time:Date.now()});G.recentDrops=G.recentDrops.slice(0,10)}
function receive(it){if(it.legend)G.collection[it.legend]=true;let cmp=compareItem(it),curScore=setScore(G.gear),candidate={...G.gear,[it.slot]:it},newScore=setScore(candidate),action='';if(G.autoEquip&&newScore>curScore*1.012){let old=G.gear[it.slot];G.gear[it.slot]=it;action='✨ 自動装備';if(old)action+=' / '+storeItem(old,{ignoreAuto:true,forceKeep:true})}else action=storeItem(it);recordDrop(it,action,cmp);log('🎁 '+(R[it.rar]?.n||'Unknown')+' '+it.name+' / '+action);touch()}
