function compareItem(it){let a=stats(),b=stats({...G.gear,[it.slot]:it}),delta=(x,y)=>x?((y/x)-1)*100:0;return{dps:delta(a.dps,b.dps),hp:delta(a.hp,b.hp),boss:delta(a.dps*a.boss,b.dps*b.boss),mf:(b.mf-a.mf)*100,crit:(b.crit-a.crit)*100,critMult:b.critMult-a.critMult,dr:(b.dr-a.dr)*100,leech:(b.leech-a.leech)*100,first:(b.first-a.first)*100,combo:(b.combo-a.combo)*100,lastStand:(b.lastStand-a.lastStand)*100}}
function log(t){t=safeStr(t,'',180);G.log.unshift(t);G.log=G.log.slice(0,8);$('#notice').textContent=t}
function touch(){staticDirty=true}
function equipmentDropRate(type,mf=stats().mf){let base=type==='boss'?.45:type==='elite'?.30:.08;return Math.min(.75,base+Math.max(0,mf)*.10)}
function baseHp(lv=dungeonLv()){return 12*Math.pow(1.06,Math.max(0,lv-1))*(1+lv*.012)}
function baseEnemyDmg(lv=dungeonLv()){return Math.max(1,1.8*Math.pow(1.035,Math.max(0,lv-1)))}
function canNemesis(){let x=G.nemesis,f=floor();return !!(x&&G.mode==='normal'&&G.normalMode==='progress'&&x.dungeon===G.currentDungeon&&f>=Math.max(1,x.homeFloor-5)&&f<=x.homeFloor+8&&G.totalKills>=x.readyAt)}
function spawn(){if(G.deadUntil>Date.now())return;let f=floor(),d=du(),lv=G.mode==='boss'?bossLv():dungeonLv(G.currentDungeon,f),finalBoss=G.mode==='normal'&&G.normalMode==='progress'&&!G.cleared[G.currentDungeon]&&f===d.clearFloor,boss=G.mode==='boss'||finalBoss,elite=false,nem=false,icon,name,hp=baseHp(lv)*d.hp,dmg=baseEnemyDmg(lv)*d.dmg,es=d.speed,gm=d.gold,min=1,rank='NORMAL';if(boss){icon=d.bossIcon;name=d.boss;hp*=8.5;dmg*=2.2;gm*=5;min=2;rank=G.mode==='boss'?'BOSS DUNGEON':'FINAL BOSS';G.hp=stats().hp}else if(canNemesis()&&Math.random()<.12){let n=G.nemesis;nem=true;elite=true;icon=n.icon;name=n.name;hp*=6.5*(1+n.rank*.38);dmg*=1.7*(1+n.rank*.14);gm*=7;min=3;rank='NEMESIS '+n.rank}else{let e=E[Math.floor(Math.random()*E.length)];icon=e[0];name=e[1];if(Math.random()<d.elite){elite=true;let ts=[['巨大な',1.7,1,1],['黄金の',1.25,.9,2.5],['狂暴な',1.35,1.5,1.3],['変異した',1.45,1.1,1.5]],t=ts[Math.floor(Math.random()*ts.length)];name=t[0]+name;hp*=4*t[1];dmg*=1.4;es*=t[2];gm*=3.5*t[3];min=2;rank='ELITE'}}G.enemy={boss,finalBoss,bossDungeon:G.mode==='boss',elite,nem,icon,name,hp,maxHp:hp,dmg,enemySpeed:es,goldM:gm,minRare:min,rank,hits:0,dungeonLv:lv};ht=0;et=0}
function tierForDungeon(id=G.currentDungeon){let chances=TIER_CHANCE[id]||TIER_CHANCE.sewer,r=Math.random(),sum=0;for(let i=0;i<4;i++){sum+=chances[i];if(r<sum)return i+1}return 4}
function affAtTier(id,t){let a=A[id],tier=clamp(Math.floor(t),1,4),z=a.tiers[tier-1],v=z[0]+Math.random()*(z[1]-z[0]);return{id,tier,value:v/100}}
function aff(id,dungeon=G.currentDungeon){return affAtTier(id,tierForDungeon(dungeon))}
function maybeGoldenize(it){let midas=legendItem(G.gear,'midas'),chance=midas?legendRollValue(midas):0;if(!chance||!it.aff?.length||Math.random()>=chance)return it;it.golden=true;it.aff=it.aff.map(x=>affAtTier(x.id,Math.min(4,x.tier+1)));return it}
function rarity(min=1){let s=stats(),r=Math.random()+s.mf*.22,v=r>.997?5:r>.955?4:r>.80?3:r>.48?2:1;return Math.max(min,v)}
function pickBase(slot,leg=null){if(leg&&L[leg]?.base)return L[leg].base;let pool=BASE_BY_SLOT[slot]||[];return pool[Math.floor(Math.random()*pool.length)]}
function makeItem(min=1,leg=null,baseFloor=dungeonLv()){let slot=leg?L[leg].slot:Object.keys(SLOTS)[Math.floor(Math.random()*Object.keys(SLOTS).length)],rar=leg?4:rarity(min),il=Math.max(1,baseFloor+Math.floor(Math.random()*5)-2),mm=R[rar].m,base=pickBase(slot,leg),bd=B[base],pool=[...AFFIX_POOL];for(const b of du().bias)if(AFFIX_POOL.includes(b))pool.push(b,b);let used=new Set(),aa=[];while(aa.length<Math.min(4,rar-1)){let id=pool[Math.floor(Math.random()*pool.length)];if(used.has(id))continue;used.add(id);aa.push(aff(id))}let now=Date.now(),it={id:now.toString(36)+Math.random().toString(36).slice(2),slot,base,legacy:false,legacyLegend:false,rar,ilvl:il,name:leg?L[leg].n:bd.n,atk:0,hp:0,speed:0,mf:0,aff:aa,legend:leg,legendRoll:leg&&!L[leg].legacyOnly?rollLegendValue(leg):null,golden:false,enh:0,invested:0,locked:false,isNew:true,obtainedAt:now,sourceDungeon:G.currentDungeon,sourceDungeonLv:dungeonLv(G.currentDungeon,floor())};if(slot==='weapon')it.atk=Math.floor((3+il*.52)*mm*(bd.atk||1));if(slot==='head'){it.hp=Math.floor((3+il*.45)*mm*(bd.hp||1));it.atk=Math.floor(il*.045*mm*(bd.atk||0));it.mf=Math.floor((1+il*.025)*mm*(bd.mf||0))}if(slot==='chest'){it.hp=Math.floor((7+il*.90)*mm*(bd.hp||1));it.atk=Math.floor(il*.035*mm*(bd.atk||0))}if(slot==='feet'){it.hp=Math.floor((2+il*.32)*mm*(bd.hp||1));it.speed=(rar>=2?rar*.45:0)*(bd.speed||0);it.mf=Math.floor((1+il*.02)*mm*(bd.mf||0))}if(slot==='trinket'){it.mf=Math.floor((1+il*.045)*mm*(bd.mf||1));it.atk=Math.floor(il*.05*mm*(bd.atk||1));it.hp=Math.floor(il*.18*mm*(bd.hp||1))}return maybeGoldenize(it)}
function salvageValue(it){return Math.max(1,Math.floor((R[it.rar]?.m||1)*(2+it.ilvl*.12)+(it.invested||0)*.70))}
function protectedItem(it){return !!(it&&it.locked)}
function slotInventory(slot){return G.inv.filter(x=>x.slot===slot)}
function slotHasRoom(slot){return slotInventory(slot).length<SLOT_CAP}
function canStoreReplaced(slot){return slotHasRoom(slot)||slotInventory(slot).some(x=>!x.locked)}
function itemValue(it){if(!it)return-1;return setScore({...G.gear,[it.slot]:it},'balanced')+(it.legend?500:0)+(it.rar>=4?700:0)+(it.rar>=5?300:0)}
function recordAffixes(it){if(!it)return;G.affixRecords=G.affixRecords||{};for(const x of it.aff||[]){let r=G.affixRecords[x.id];if(!r||x.tier>r.tier||(x.tier===r.tier&&x.value>r.value))G.affixRecords[x.id]={tier:x.tier,value:x.value}}}
function recordLegendaryRoll(it){if(!isUniqueLegendary(it))return;G.legendRecords=G.legendRecords||{};let v=legendRollValue(it),old=G.legendRecords[it.legend];if(old==null||v>old)G.legendRecords[it.legend]=v}
function legendaryKept(id){return Object.values(G.gear).some(x=>x?.id===id)||G.inv.some(x=>x.id===id)||(G.legendaryStash||[]).some(x=>x.id===id)}
function stashLegendary(it){G.legendaryStash=G.legendaryStash||[];let same=G.legendaryStash.findIndex(x=>x.legend===it.legend);if(same>=0){let old=G.legendaryStash[same];if(legendRollValue(it)>legendRollValue(old)){G.legendaryStash[same]=it;return'⭐ 保留箱：同名の高ロール品へ更新'}return'💩 保留箱の同名品より低ロールのためポロッ'}if(G.legendaryStash.length<LEGEND_STASH_CAP){G.legendaryStash.push(it);return'⭐ Legendary保留箱へ退避'}return'💩 Legendary保留箱 3/3 のためポロッ'}
function storeItem(it,{ignoreAuto=false,forceKeep=false}={}){if(!it)return'破棄';recordAffixes(it);let same=slotInventory(it.slot),evictable=same.filter(x=>!x.locked);if(isUniqueLegendary(it)){if(same.length<SLOT_CAP){G.inv.push(it);return'保管'}if(evictable.length){let worst=evictable.sort((a,b)=>itemValue(a)-itemValue(b))[0];if(forceKeep||itemValue(it)>itemValue(worst)){let i=G.inv.findIndex(x=>x.id===worst.id),v=salvageValue(worst);G.inv.splice(i,1);G.sludge+=v;G.inv.push(it);return SLOTS[it.slot]+' 満杯：低価値装備を入替分解 → 🧪 +'+v}}return stashLegendary(it)}if(!ignoreAuto&&!it.locked&&it.rar<=G.autoSalvage){let v=salvageValue(it);G.sludge+=v;return'自動分解 → 🧪 +'+v}if(same.length<SLOT_CAP){G.inv.push(it);return'保管'}if(forceKeep||it.locked){if(evictable.length){let worst=evictable.sort((a,b)=>itemValue(a)-itemValue(b))[0],i=G.inv.findIndex(x=>x.id===worst.id),v=salvageValue(worst);G.inv.splice(i,1);G.sludge+=v;G.inv.push(it);return'旧装備保護のため低価値装備を分解 → 🧪 +'+v}G.inv.push(it);return'全16枠ロック中のため一時的に上限超過で保管'}if(!evictable.length){let v=salvageValue(it);G.sludge+=v;return SLOTS[it.slot]+' 16/16（全ロック）→ 自動分解 🧪 +'+v}let worst=evictable.sort((a,b)=>itemValue(a)-itemValue(b))[0];if(itemValue(it)>itemValue(worst)){let i=G.inv.findIndex(x=>x.id===worst.id),v=salvageValue(worst);G.inv.splice(i,1);G.sludge+=v;G.inv.push(it);return SLOTS[it.slot]+' 満杯：低価値装備を入替分解 → 🧪 +'+v}let v=salvageValue(it);G.sludge+=v;return SLOTS[it.slot]+' 満杯：自動分解 → 🧪 +'+v}
function recordDrop(it,action,cmp){recordAffixes(it);G.recentDrops.unshift({item:JSON.parse(JSON.stringify(it)),action,cmp,time:Date.now()});G.recentDrops=G.recentDrops.slice(0,10)}
function receive(it){recordAffixes(it);let cmp=compareItem(it),curScore=setScore(G.gear),candidate={...G.gear,[it.slot]:it},newScore=setScore(candidate),action='',old=G.gear[it.slot],canSwap=!old||canStoreReplaced(it.slot);if(G.autoEquip&&canSwap&&newScore>curScore*1.05){G.gear[it.slot]=it;it.isNew=false;action='✨ 自動装備';if(old)action+=' / '+storeItem(old,{ignoreAuto:true,forceKeep:true})}else action=storeItem(it);let kept=legendaryKept(it.id);if(it.legend&&kept)G.collection[it.legend]=true;if(kept)recordLegendaryRoll(it);recordDrop(it,action,cmp);log('🎁 '+(R[it.rar]?.n||'Unknown')+' '+it.name+' / '+action);touch()}
