function ensureV22State(){G.v=223;G.flushGauge=Math.max(0,num(G.flushGauge,0));if(!Number.isFinite(G.anchorFloor))G.anchorFloor=1;G.anchorFloor=Math.max(1,1+10*Math.floor((G.anchorFloor-1)/10));if(!G.startFloor||typeof G.startFloor!=='object')G.startFloor=maps(1);for(const id of Object.keys(D)){let maxStart=Math.min(G.anchorFloor,Math.max(1,(G.best[id]||1)-(((G.best[id]||1)-1)%10)));let f=Number(G.startFloor[id])||1;f=Math.max(1,1+10*Math.floor((f-1)/10));G.startFloor[id]=Math.min(f,maxStart)}for(const sl of Object.keys(SLOTS))if(!(sl in G.gear))G.gear[sl]=null;return G}
function itemHtml(it,withCmp=false){let cmp=withCmp?compareItem(it):null,rar=R[it.rar]?.n||'Unknown',slot=SLOTS[it.slot]||'不明',legend=it.legend&&L[it.legend]?L[it.legend]:null,base=it.base&&B[it.base]?B[it.base]:null,implicit=base?.implicit?.text;return `<div class='r${it.rar} font-medium'>${it.locked?'🔒 ':''}${esc(rar)} ${esc(it.name)}${it.enh?' +'+it.enh:''}</div><div class='text-xs text-[var(--viz-muted)]'>Lv.${num(it.ilvl,1)} / ${esc(slot)}${it.legacy?' / Legacy':''}</div>${implicit?`<div class='mt-2 rounded-lg border border-[var(--viz-border)] p-2 text-xs'>◆ Implicit：${esc(implicit)}</div>`:''}<div class='text-xs mt-1'>⚔️ +${num(it.atk)}　❤️ +${num(it.hp)}　⚡ +${num(it.speed)}　🎁 +${num(it.mf)}</div>${(it.aff||[]).map(x=>`<div class='text-xs mt-1'>${esc(affText(x))}</div>`).join('')}${legend?`<div class='mt-2 rounded-lg border border-[var(--viz-border)] p-2 text-xs r4'>★ 固有：${esc(legend.desc)}</div>`:''}${cmp?`<div class='mt-2 text-xs text-[var(--viz-muted)]'>装備比較：DPS ${cmp.dps>=0?'+':''}${cmp.dps.toFixed(1)}% / HP ${cmp.hp>=0?'+':''}${cmp.hp.toFixed(1)}% / Boss ${cmp.boss>=0?'+':''}${cmp.boss.toFixed(1)}% / MF ${cmp.mf>=0?'+':''}${cmp.mf.toFixed(1)}pt</div>`:''}`}
function enhance(slot){let it=G.gear[slot];if(!it)return;let c=8+(it.enh||0)*7;if(G.sludge<c){log('汚泥不足。');return}G.sludge-=c;it.enh=(it.enh||0)+1;it.invested=(it.invested||0)+c;log('🧪 '+it.name+' +'+it.enh);touch()}
function reroll(slot){let it=G.gear[slot];if(!it||!it.aff?.length)return;let c=12+it.rar*5;if(G.sludge<c){log('汚泥不足。');return}let index=it.aff.reduce((best,x,i,a)=>x.tier<a[best].tier?i:best,0),used=new Set(it.aff.map(x=>x.id)),pool=AFFIX_POOL.filter(id=>!used.has(id));if(!pool.length)return;G.sludge-=c;it.aff[index]=aff(pool[Math.floor(Math.random()*pool.length)]);log('🎲 '+it.name+' の最低Tier Affixを再抽選。');touch()}
function equipItem(id){let i=G.inv.findIndex(x=>x.id===id);if(i<0)return;let it=G.inv[i],old=G.gear[it.slot];G.gear[it.slot]=it;G.inv.splice(i,1);if(old)storeItem(old,{ignoreAuto:true,forceKeep:true});G.hp=Math.min(G.hp,stats().hp);log('🧰 '+it.name+' を装備。旧装備は自動分解しません。');touch()}
function toggleLock(id){let it=G.inv.find(x=>x.id===id);if(it){it.locked=!it.locked;touch()}}
function salvageOne(id){let i=G.inv.findIndex(x=>x.id===id);if(i<0)return;let it=G.inv[i];if(protectedItem(it)){log('保護・Legendary・Mythicは個別分解できません。');return}let v=salvageValue(it);G.inv.splice(i,1);G.sludge+=v;log('🧪 '+it.name+' 分解 / +'+v);touch()}
function equipBest(){let slots=Object.keys(SLOTS),pools={};for(const sl of slots){pools[sl]=[G.gear[sl],...G.inv.filter(x=>x.slot===sl)].filter(Boolean);if(!pools[sl].length)pools[sl]=[null]}let bestGear={...G.gear},bestScore=setScore(bestGear),tested=0;function walk(i,gear){if(i>=slots.length){let sc=setScore(gear);tested++;if(sc>bestScore){bestScore=sc;bestGear={...gear}}return}let sl=slots[i];for(const it of pools[sl])walk(i+1,{...gear,[sl]:it})}walk(0,{});let oldGear={...G.gear},selected=new Set(Object.values(bestGear).filter(Boolean).map(x=>x.id)),inv=G.inv.filter(x=>!selected.has(x.id));for(const it of Object.values(oldGear))if(it&&!selected.has(it.id)&&!inv.some(x=>x.id===it.id))inv.push(it);G.inv=inv;G.gear=bestGear;G.hp=Math.min(G.hp,stats().hp);log('✨ '+tested+'通り比較して全体最適装備に更新。旧装備は保持。');touch()}
function salvageLow(){let keep=[],gain=0,count=0;for(const it of G.inv){if(!protectedItem(it)&&it.rar<=2){gain+=salvageValue(it);count++}else keep.push(it)}G.inv=keep;G.sludge+=gain;log('🧪 '+count+'個分解 / +'+gain);touch()}
function selectDungeon(id,mode='normal'){if(!D[id]||gb()<D[id].unlock)return;let cleared=Math.floor((G.best[id]-1)/10)*10;if(mode==='boss'&&cleared<10){log('Boss周回は10F撃破後に解禁。');return}G.currentDungeon=id;G.mode=mode;if(mode==='boss')G.farmFloor=cleared;G.enemy=null;G.deadUntil=0;G.hp=stats().hp;spawn();tab('battle');log(D[id].icon+' '+D[id].name+(mode==='boss'?' Boss周回':' 探索')+'へ。');touch()}
function chooseTrait(id){if(G.traitPoints<1||!G.traitChoices.includes(id))return;G.traits[id]=(G.traits[id]||0)+1;G.traitPoints--;rollTraits();log('🧬 '+T[id].n+' Rank '+G.traits[id]);touch()}
function upgradeCost(k){return Math.floor(U[k].base*Math.pow(1.62,G.baseUp[k]))}
function buyUpgrade(k){let c=upgradeCost(k);if(G.gold<c){log('Gold不足。');return}if(k==='speed'&&stats().sp>=5){log('攻撃速度は上限 5.00/s。');return}if(k==='luck'&&stats().mf>=.85){log('Magic Findは上限 85%。');return}G.gold-=c;G.baseUp[k]++;G.hp=Math.min(stats().hp,G.hp+(k==='hp'?9:0));touch()}
function soulCost(k){return Math.ceil(2*Math.pow(1.5,G.soulTree[k]))}
function buySoul(k){let c=soulCost(k);if(G.souls<c){log('魂不足。');return}G.souls-=c;G.soulTree[k]++;touch()}
function nextAnchorFloor(){return G.anchorFloor+10}
function checkpointCost(f=nextAnchorFloor()){let n=Math.max(1,Math.floor((f-1)/10));if(n===1)return 2;if(n===2)return 5;return 10*Math.pow(2,n-3)}
function buyCheckpoint(){let f=nextAnchorFloor(),c=checkpointCost(f);if(gb()<f){log('まずどこかのダンジョンで '+f+'F に到達する必要があります。');return}if(G.souls<c){log('魂不足。');return}G.souls-=c;G.anchorFloor=f;for(const id of Object.keys(D)){let maxStart=Math.min(G.anchorFloor,Math.max(1,G.best[id]-((G.best[id]-1)%10)));if(G.startFloor[id]>maxStart)G.startFloor[id]=maxStart}log('⚓ '+f+'F 魂チェックポイントを恒久解放。');touch()}
function setStartFloor(id,f){if(!D[id])return;f=1+10*Math.floor((Number(f)-1)/10);let maxStart=Math.min(G.anchorFloor,Math.max(1,G.best[id]-((G.best[id]-1)%10)));if(f<1||f>maxStart)return;G.startFloor[id]=f;log('⚓ '+D[id].name+' のFLUSH後開始地点を '+f+'F に設定。');touch()}
function flushGain(){ensureV22State();if(G.flushGauge<100)return 0;return Math.max(1,Math.floor(1+1.5*Math.pow(G.flushGauge/100,.6)))}
function flush(){ensureV22State();if(G.flushGauge<100){log('FLUSHゲージが100%必要。');return}let gain=flushGain(),old=G,keep={souls:old.souls+gain,prestiges:old.prestiges+1,totalKills:old.totalKills,bossKills:old.bossKills,eliteKills:old.eliteKills,nemesisKills:old.nemesisKills,best:old.best,pity:old.pity,milestones:old.milestones,mastery:old.mastery,collection:old.collection,soulTree:old.soulTree,nemesis:old.nemesis};G=fresh(keep);G.sludge=old.sludge;G.gear=old.gear;G.inv=old.inv;G.autoEquip=old.autoEquip;G.autoSalvage=old.autoSalvage;G.equipFocus=old.equipFocus;G.simSpeed=old.simSpeed;G.currentDungeon=old.currentDungeon;G.anchorFloor=old.anchorFloor;G.startFloor={...old.startFloor};G.recentDrops=old.recentDrops;G.offline=old.offline;G.paused=old.paused;G.flushGauge=0;for(const id of Object.keys(D))G.runFloor[id]=G.startFloor[id]||1;G.cycleBest={...G.runFloor};ensureV22State();G.hp=stats().hp;spawn();log('🚽 FLUSH！ 魂 +'+gain+'。装備・汚泥・恒久育成は維持。');touch()}
