function itemHtml(it,withCmp=false){let cmp=withCmp?compareItem(it):null;return `<div class='r${it.rar} font-medium'>${it.locked?'🔒 ':''}${R[it.rar].n} ${it.name}${it.enh?' +'+it.enh:''}</div><div class='text-xs text-[var(--viz-muted)]'>Lv.${it.ilvl} / ${SLOTS[it.slot]}</div><div class='text-xs mt-1'>⚔️ +${it.atk}　❤️ +${it.hp}　⚡ +${it.speed}　🎁 +${it.mf}</div>${(it.aff||[]).map(x=>`<div class='text-xs mt-1'>${affText(x)}</div>`).join('')}${it.legend?`<div class='mt-2 rounded-lg border border-[var(--viz-border)] p-2 text-xs r4'>★ 固有：${L[it.legend].desc}</div>`:''}${cmp?`<div class='mt-2 text-xs text-[var(--viz-muted)]'>装備比較：DPS ${cmp.dps>=0?'+':''}${cmp.dps.toFixed(1)}% / HP ${cmp.hp>=0?'+':''}${cmp.hp.toFixed(1)}% / Boss ${cmp.boss>=0?'+':''}${cmp.boss.toFixed(1)}% / MF ${cmp.mf>=0?'+':''}${cmp.mf.toFixed(1)}pt</div>`:''}`}
function enhance(slot){let it=G.gear[slot];if(!it)return;let c=8+(it.enh||0)*7;if(G.sludge<c){log('汚泥不足。');return}G.sludge-=c;it.enh=(it.enh||0)+1;it.invested=(it.invested||0)+c;log('🧪 '+it.name+' +'+it.enh);touch()}
function reroll(slot){let it=G.gear[slot];if(!it||!it.aff?.length)return;let c=12+it.rar*5;if(G.sludge<c){log('汚泥不足。');return}let index=it.aff.reduce((best,x,i,a)=>x.tier<a[best].tier?i:best,0),used=new Set(it.aff.map(x=>x.id)),pool=Object.keys(A).filter(id=>!used.has(id));if(!pool.length)return;G.sludge-=c;it.aff[index]=aff(pool[Math.floor(Math.random()*pool.length)],it.ilvl,it.rar);log('🎲 '+it.name+' の最低Tier Affixを再抽選。');touch()}
function equipItem(id){let i=G.inv.findIndex(x=>x.id===id);if(i<0)return;let it=G.inv[i],old=G.gear[it.slot];G.gear[it.slot]=it;G.inv.splice(i,1);if(old)storeItem(old);G.hp=Math.min(G.hp,stats().hp);touch()}
function toggleLock(id){let it=G.inv.find(x=>x.id===id);if(it){it.locked=!it.locked;touch()}}
function salvageOne(id){let i=G.inv.findIndex(x=>x.id===id);if(i<0)return;let it=G.inv[i];if(protectedItem(it)){log('保護・Legendary・Mythicは個別分解できません。');return}let v=salvageValue(it);G.inv.splice(i,1);G.sludge+=v;log('🧪 '+it.name+' 分解 / +'+v);touch()}
function equipBest(){for(const sl of Object.keys(SLOTS)){let pool=G.inv.filter(x=>x.slot===sl);let best=null,bestScore=setScore(G.gear);for(const it of pool){let sc=setScore({...G.gear,[sl]:it});if(sc>bestScore){best=it;bestScore=sc}}if(best){let old=G.gear[sl],i=G.inv.findIndex(x=>x.id===best.id);G.gear[sl]=best;G.inv.splice(i,1);if(old)storeItem(old)}}G.hp=Math.min(G.hp,stats().hp);log('✨ 現在の基準で最適装備に更新。');touch()}
function salvageLow(){let keep=[],gain=0,count=0;for(const it of G.inv){if(!protectedItem(it)&&it.rar<=2){gain+=salvageValue(it);count++}else keep.push(it)}G.inv=keep;G.sludge+=gain;log('🧪 '+count+'個分解 / +'+gain);touch()}
function selectDungeon(id,mode='normal'){if(gb()<D[id].unlock)return;G.currentDungeon=id;G.mode=mode;if(mode==='boss'){let cleared=Math.floor((G.best[id]-1)/10)*10;if(cleared<10)return;G.farmFloor=cleared}G.enemy=null;G.deadUntil=0;G.hp=stats().hp;spawn();tab('battle');log(D[id].icon+' '+D[id].name+(mode==='boss'?' Boss周回':' 探索')+'へ。');touch()}
function chooseTrait(id){if(G.traitPoints<1||!G.traitChoices.includes(id))return;G.traits[id]=(G.traits[id]||0)+1;G.traitPoints--;rollTraits();log('🧬 '+T[id].n+' Rank '+G.traits[id]);touch()}
function upgradeCost(k){return Math.floor(U[k].base*Math.pow(1.62,G.baseUp[k]))}
function buyUpgrade(k){let c=upgradeCost(k);if(G.gold<c){log('Gold不足。');return}if(k==='speed'&&stats().sp>=5){log('攻撃速度は上限 5.00/s。');return}if(k==='luck'&&stats().mf>=.85){log('Magic Findは上限 85%。');return}G.gold-=c;G.baseUp[k]++;G.hp=Math.min(stats().hp,G.hp+(k==='hp'?9:0));touch()}
function soulCost(k){return 1+G.soulTree[k]}
function buySoul(k){let c=soulCost(k);if(G.souls<c){log('魂不足。');return}G.souls-=c;G.soulTree[k]++;touch()}
function flushGain(){return Math.max(1,Math.floor(gb()/20)+Math.floor(G.lv/25)+Math.floor(G.mastery/4))}
function flush(){if(gb()<30)return;let gain=flushGain(),keep={souls:G.souls+gain,prestiges:G.prestiges+1,totalKills:G.totalKills,bossKills:G.bossKills,eliteKills:G.eliteKills,nemesisKills:G.nemesisKills,best:G.best,pity:G.pity,milestones:G.milestones,mastery:G.mastery,collection:G.collection,soulTree:G.soulTree,nemesis:G.nemesis};G=fresh(keep);G.hp=stats().hp;spawn();log('🚽 FLUSH！ 魂 +'+gain+'。敵は転生回数で強化されません。');touch()}
